name: Netology-CICD

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip3 install --no-cache-dir --upgrade -r requirements.txt

      - name: Code linting
        run: |
          flake8 stocks_products
          flake8 logistic
